#!/bin/bash
set -e

# Copy a default configuration into place if not present
if ! [ -f /opt/openresty/conf/nginx.conf ]; then
  mkdir -p /opt/openresty/conf
  mkdir -p /opt/openresty/logs
  mdkir -p /opt/openresty/tmp
  cp -upR "/usr/local/openresty/nginx/conf/." "/opt/openresty/conf/nginx/"
  echo "daemon off;" >> "/opt/openresty/conf/nginx.conf"
fi

command="$@"

${command}
